# Generated by Django 5.2.7 on 2025-10-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_id',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
