# Generated by Django 5.2.7 on 2025-10-20 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_city_profile_country_profile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('project_location', models.CharField(blank=True, max_length=200)),
                ('description_html', models.TextField(blank=True)),
                ('sample_by', models.CharField(blank=True, max_length=200)),
                ('receiving_date', models.DateField(blank=True, null=True)),
                ('sample_description', models.TextField(blank=True)),
                ('spec_document', models.FileField(blank=True, null=True, upload_to='lab_requests/')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('on-test', 'On-Test'), ('ready-collect', 'Ready To Collect'), ('report-delivered', 'Report Delivered')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=120)),
                ('test_name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.labtestrequest')),
            ],
        ),
    ]
