# Generated by Django 5.2.7 on 2025-10-20 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_labtestrequest_labtestitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('description_html', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='consultancy_requests/')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('on-test', 'On-Test'), ('ready-collect', 'Ready To Collect'), ('report-delivered', 'Report Delivered')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
