# Generated by Django 5.2.7 on 2025-10-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_consultancyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancyrequest',
            name='report_verification_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='report_verification_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
