# Generated by Django 5.2.7 on 2025-10-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_consultancyrequest_report_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancyrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consultancyrequest',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
